name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: Interpreter

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: Interpreter

    - name: Run tests
      run: ./gradlew test
      working-directory: Interpreter